language: node_js
node_js:
    - "lts/*"
    
script: npm run build

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: dist
    keep-history: true
    on: 
        branch: master
